name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: " 👋 @{{ author }}

            Thank you for raising an issue. We will investigate into the matter and get back to you as soon as possible.

            Please make sure you have given us as much context as possible."
        pr-message: "Hello👋 @{{ author }}, I hope you are doing well!
            <br>
            Thank you for raising your pull request and contributing to our Community 🎉

            Please make sure you have followed our contributing guidelines. We will review it as soon as possible."
